create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_name text not null check (char_length(user_name) between 1 and 20),
  body text not null check (char_length(body) between 1 and 300),
  created_at timestamptz not null default now()
);

alter table public.messages enable row level security;

drop policy if exists "workshop read messages" on public.messages;
create policy "workshop read messages"
on public.messages
for select
to anon
using (true);

drop policy if exists "workshop insert messages" on public.messages;
create policy "workshop insert messages"
on public.messages
for insert
to anon
with check (true);

do $$
begin
  alter publication supabase_realtime add table public.messages;
exception
  when duplicate_object then null;
end $$;

insert into public.messages (user_name, body)
select seed.user_name, seed.body
from (
  values
    ('Taro', 'こんにちは！'),
    ('Hanako', 'やっほー'),
    ('Doer', 'LINEを作ろう')
) as seed(user_name, body)
where not exists (select 1 from public.messages);
